site_name: XCONFIGURE
docs_dir: .
pages:
- Home: index.md
- Applications:
  - CP2K: cp2k/README.md
  - ELPA: elpa/README.md
  - LIBINT: libint/README.md
  - LIBXC: libxc/README.md
  - LIBXSMM: libxsmm/README.md
  - QE: qe/README.md

