theme: readthedocs
theme_dir: .theme
docs_dir: config
site_name: XCONFIGURE
site_author: Hans Pabst
copyright: Copyright (c) 2013-2017, XCONFIGURE <a href="http://xconfigure.readthedocs.io/LICENSE/">Contributors</a>.
site_description: High-Performance configuration patterns and recipes.
repo_url: https://github.com/hfp/xconfigure.git
markdown_extensions:
- toc:
    permalink: True
extra_javascript:
- search.js
extra_css:
- style.css

pages:
- index.md
- Applications:
  - CP2K: cp2k/README.md
  - ELPA: elpa/README.md
  - LIBINT: libint/README.md
  - LIBXC: libxc/README.md
  - LIBXSMM: libxsmm/README.md
  - QE: qe/README.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md

