site_name: XCONFIGURE
site_author: Hans Pabst
copyright: Copyright (c) 2013-2020, XCONFIGURE <a href="https://xconfigure.readthedocs.io/LICENSE/">Contributors</a>.
site_description: High-Performance configuration patterns and recipes.
repo_url: https://github.com/hfp/xconfigure
edit_uri: edit/master/config
docs_dir: config

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 2
    title: None
extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

nav:
- index.md
- Applications:
  - CP2K: cp2k/README.md
  - ELPA: elpa/README.md
  - LIBINT: libint/README.md
  - LIBXC: libxc/README.md
  - LIBXSMM: libxsmm/README.md
  - TF: tf/README.md
  - QE: qe/README.md
- About:
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
